name: data-curation

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python==3.10
  - ipython
  - datrie
  - pip
  - pip:
    - opencv-python
    - polars==0.16.18
    - requests
    - tqdm
    - pyarrow
    - gradio
    - beautifulsoup4
    - Pillow
    - pandas
    - onnxruntime
    - torch
    - onnxruntime-gpu
